name: flutter_native_strings
description: A command-line tool that simplifies the task of adding native Android and iOS string resources to your Flutter app.
version: 0.0.1
repository: https://github.com/victoreronmosele/flutter-native-strings

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  xml: ^4.5.1
  file: ^5.2.1

dev_dependencies:
  mockito: ^4.1.3
  test: ^1.16.0-nullsafety.5
